{% set name = "tokenize-rt" %}
{% set version = "5.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tokenize_rt-{{ version }}.tar.gz
  sha256: 9fe80f8a5c1edad2d3ede0f37481cc0cc1538a2f442c9c2f9e4feacd2792d054

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tokenize-rt = tokenize_rt:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - tokenize_rt
  commands:
    - tokenize-rt --help

about:
  home: https://github.com/asottile/tokenize-rt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A wrapper around the stdlib `tokenize` which roundtrips.

extra:
  recipe-maintainers:
    - sterlingbaldwin
    - deadsnakes-issues-bot
    - nicoddemus
