{% set name = "tokenize-rt" %}
{% set version = "6.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tokenize_rt-{{ version }}.tar.gz
  sha256: b9711bdfc51210211137499b5e355d3de5ec88a85d2025c520cbb921b5194367

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tokenize-rt = tokenize_rt:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - tokenize_rt
  commands:
    - tokenize-rt --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asottile/tokenize-rt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A wrapper around the stdlib `tokenize` which roundtrips.

extra:
  recipe-maintainers:
    - sterlingbaldwin
    - deadsnakes-issues-bot
    - nicoddemus
